database: 
  host: localhost
  user: root
  password: password
  name: episode
ftp: 
  active: false
  host: localhost
  user: guest
  password: 
modules: 
  core: 
    @version: 1.0.1
    title: EpisodeCMS
    divider: " - "
    description: Content Management System
    keywords: >
      EpisodeCMS, CakePHP, CMS, freeware, open-source, download, php
    demo: true
    maintance: false
  gallery: 1.0.1
  dev: 1.0.1
  blog: 1.0.1
frontend: 
  theme: default
backend: 
  theme: _classic
menus: 
  main: 
    Home: 
      @link: /
    Blog: 
      @link: /blog/
    Portfolio: 
      @link: /portfolio/
    About: 
      @link: /page/about
admin-language: eng
debug: 4