---
database: 
  host: localhost
  database: directive
  login: root
  password: password
modules: 
  core: 
    title: Directive
    description: 
    keywords: 
    maintance: 0
  directive: 1.0.1
debug: 4