---
setup: false
modules: 
  dev: 1.0.1
title: EpisodeCMS
version: 1.0.1
description: EpisodeCMS official site
content: '* EpisodeCMS official site'
routes: 
  "/modules/:slug": 
    controller: modules
    action: view
    pass: 
      - slug
    slug: '[^/]+'
  "/project/:slug:/edit": 
    controller: module
    action: edit
    pass: 
      - slug
    slug: '[^/]+'
  /admin/EpisodeModules: 
    controller: modules
    action: admin_browse
admin: 
  Content: 
    Modules: 
      _link: 
        controller: modules
        action: admin_browse
theme: default
theme_path: >
  /var/www/episode/projects/EpisodeCMS/themes/default
