title: Developer Pack
version: 1.0.1
description:|
  Developer Pack designed for quick deploying modules for web applications.
routes:
    /admin/dev/:
        controller:dev
        action:index
install:
  method:/dev/install
uninstall:
  method:/dev/uninstall