---
setup: false
modules: 
  blog: 1.0.1
  dev: 1.0.1
title: empty
description: empty project
content: '* empty project'
version: 0
theme: default
theme_path: >
  C:\projects\episode\modules\core\themes\default
