---
setup: false
modules: 
  blog: 1.0.1
  dev: 1.0.1
  portfolio: 1.0.1
  newsletter: 
title: empty
description: empty project
version: 0
theme: default
theme_path: >
  /var/www/episode/modules/core/themes/default
