---
setup: false
modules: 
  blog: 1.0.1
  dev: 1.0.1
  recipes: 1.0.1
  wiki: 1.0.1
  banners: 
  portfolio: 
  translations: 
debug: 4
title: cook2.me
description: >
  Кулинарная
  социальная сеть
keywords: 
routes: 
  /: 
    controller: viewer
    action: index
    model: recipe
    pass: 
      - model
version: 0
theme: default
theme_path: >
  /var/www/episode/projects/cook2.me/themes/default
