---
debug: 4
setup: false
modules: 
  banners: 1.0.1
  blog: 1.0.1
  dev: 1.0.1
  recipes: 1.0.1
  comments: 1.0.1
title: cook2.me
description: >
  Кулинарная
  социальная сеть
keywords: 
ui: 
  admin: 
    _css: 
      - admin
routes: 
  /: 
    controller: viewer
    action: index
    model: recipe
    pass: 
      - model
version: 0
theme: default
theme_path: >
  C:\projects\episode\projects\cook2.me\themes\default
